/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// noinspection JSUnusedGlobalSymbols
// Generated by unplugin-auto-import
// biome-ignore lint: disable
export {}
declare global {
  const EffectScope: (typeof import('vue'))['EffectScope']
  const Storage: (typeof import('./src/utils/storage'))['Storage']
  const acceptHMRUpdate: (typeof import('pinia'))['acceptHMRUpdate']
  const addClass: (typeof import('./src/utils/domUtils'))['addClass']
  const browserType: (typeof import('./src/utils/browserType'))['default']
  const cancelRaf: (typeof import('./src/utils/index'))['cancelRaf']
  const computed: (typeof import('vue'))['computed']
  const createApp: (typeof import('vue'))['createApp']
  const createPinia: (typeof import('pinia'))['createPinia']
  const customRef: (typeof import('vue'))['customRef']
  const debounce: (typeof import('./src/utils/index'))['debounce']
  const deepMerge: (typeof import('./src/utils/index'))['deepMerge']
  const defineAsyncComponent: (typeof import('vue'))['defineAsyncComponent']
  const defineComponent: (typeof import('vue'))['defineComponent']
  const defineStore: (typeof import('pinia'))['defineStore']
  const devMode: (typeof import('./src/utils/env'))['devMode']
  const downloadByUrl: (typeof import('./src/utils/downloadFile'))['downloadByUrl']
  const effectScope: (typeof import('vue'))['effectScope']
  const error: (typeof import('./src/utils/log'))['error']
  const formatDateMs: (typeof import('./src/utils/dateUtils'))['formatDateMs']
  const formatToDate: (typeof import('./src/utils/dateUtils'))['formatToDate']
  const formatToDateTime: (typeof import('./src/utils/dateUtils'))['formatToDateTime']
  const getAction: (typeof import('./src/apis/index'))['getAction']
  const getActivePinia: (typeof import('pinia'))['getActivePinia']
  const getAppEnvConfig: (typeof import('./src/utils/env'))['getAppEnvConfig']
  const getBoundingClientRect: (typeof import('./src/utils/domUtils'))['getBoundingClientRect']
  const getCommonStoragePrefix: (typeof import('./src/utils/env'))['getCommonStoragePrefix']
  const getCurrentInstance: (typeof import('vue'))['getCurrentInstance']
  const getCurrentScope: (typeof import('vue'))['getCurrentScope']
  const getCurrentWatcher: (typeof import('vue'))['getCurrentWatcher']
  const getEnv: (typeof import('./src/utils/env'))['getEnv']
  const getImageUrl: (typeof import('./src/utils/index'))['getImageUrl']
  const getStorageShortName: (typeof import('./src/utils/env'))['getStorageShortName']
  const getUrlParams: (typeof import('./src/utils/index'))['getUrlParams']
  const getViewportOffset: (typeof import('./src/utils/domUtils'))['getViewportOffset']
  const h: (typeof import('vue'))['h']
  const hackCss: (typeof import('./src/utils/domUtils'))['hackCss']
  const hasClass: (typeof import('./src/utils/domUtils'))['hasClass']
  const inject: (typeof import('vue'))['inject']
  const is: (typeof import('./src/utils/is/index'))['is']
  const isArray: (typeof import('./src/utils/is/index'))['isArray']
  const isAsyncFunction: (typeof import('./src/utils/is/index'))['isAsyncFunction']
  const isBoolean: (typeof import('./src/utils/is/index'))['isBoolean']
  const isClient: (typeof import('./src/utils/is/index'))['isClient']
  const isDate: (typeof import('./src/utils/is/index'))['isDate']
  const isDef: (typeof import('./src/utils/is/index'))['isDef']
  const isDevMode: (typeof import('./src/utils/env'))['isDevMode']
  const isElement: (typeof import('./src/utils/is/index'))['isElement']
  const isFunction: (typeof import('./src/utils/is/index'))['isFunction']
  const isImageDom: (typeof import('./src/utils/is/index'))['isImageDom']
  const isNull: (typeof import('./src/utils/is/index'))['isNull']
  const isNullAndUnDef: (typeof import('./src/utils/is/index'))['isNullAndUnDef']
  const isNullOrUnDef: (typeof import('./src/utils/is/index'))['isNullOrUnDef']
  const isNumber: (typeof import('./src/utils/is/index'))['isNumber']
  const isObject: (typeof import('./src/utils/is/index'))['isObject']
  const isProdMode: (typeof import('./src/utils/env'))['isProdMode']
  const isPromise: (typeof import('./src/utils/is/index'))['isPromise']
  const isProxy: (typeof import('vue'))['isProxy']
  const isReactive: (typeof import('vue'))['isReactive']
  const isReadonly: (typeof import('vue'))['isReadonly']
  const isRef: (typeof import('vue'))['isRef']
  const isServer: (typeof import('./src/utils/is/index'))['isServer']
  const isShallow: (typeof import('vue'))['isShallow']
  const isString: (typeof import('./src/utils/is/index'))['isString']
  const isUnDef: (typeof import('./src/utils/is/index'))['isUnDef']
  const isUrl: (typeof import('./src/utils/index'))['isUrl']
  const isWindow: (typeof import('./src/utils/is/index'))['isWindow']
  const mapActions: (typeof import('pinia'))['mapActions']
  const mapGetters: (typeof import('pinia'))['mapGetters']
  const mapState: (typeof import('pinia'))['mapState']
  const mapStores: (typeof import('pinia'))['mapStores']
  const mapWritableState: (typeof import('pinia'))['mapWritableState']
  const markRaw: (typeof import('vue'))['markRaw']
  const nextTick: (typeof import('vue'))['nextTick']
  const off: (typeof import('./src/utils/domUtils'))['off']
  const on: (typeof import('./src/utils/domUtils'))['on']
  const onActivated: (typeof import('vue'))['onActivated']
  const onBeforeMount: (typeof import('vue'))['onBeforeMount']
  const onBeforeRouteLeave: (typeof import('vue-router'))['onBeforeRouteLeave']
  const onBeforeRouteUpdate: (typeof import('vue-router'))['onBeforeRouteUpdate']
  const onBeforeUnmount: (typeof import('vue'))['onBeforeUnmount']
  const onBeforeUpdate: (typeof import('vue'))['onBeforeUpdate']
  const onDeactivated: (typeof import('vue'))['onDeactivated']
  const onErrorCaptured: (typeof import('vue'))['onErrorCaptured']
  const onMounted: (typeof import('vue'))['onMounted']
  const onRenderTracked: (typeof import('vue'))['onRenderTracked']
  const onRenderTriggered: (typeof import('vue'))['onRenderTriggered']
  const onScopeDispose: (typeof import('vue'))['onScopeDispose']
  const onServerPrefetch: (typeof import('vue'))['onServerPrefetch']
  const onUnmounted: (typeof import('vue'))['onUnmounted']
  const onUpdated: (typeof import('vue'))['onUpdated']
  const onWatcherCleanup: (typeof import('vue'))['onWatcherCleanup']
  const once: (typeof import('./src/utils/domUtils'))['once']
  const postAction: (typeof import('./src/apis/index'))['postAction']
  const postForm: (typeof import('./src/apis/index'))['postForm']
  const prodMode: (typeof import('./src/utils/env'))['prodMode']
  const provide: (typeof import('vue'))['provide']
  const rafTimeout: (typeof import('./src/utils/index'))['rafTimeout']
  const reactive: (typeof import('vue'))['reactive']
  const readonly: (typeof import('vue'))['readonly']
  const ref: (typeof import('vue'))['ref']
  const removeClass: (typeof import('./src/utils/domUtils'))['removeClass']
  const resolveComponent: (typeof import('vue'))['resolveComponent']
  const setActivePinia: (typeof import('pinia'))['setActivePinia']
  const setMapStoreSuffix: (typeof import('pinia'))['setMapStoreSuffix']
  const setObjToUrlParams: (typeof import('./src/utils/index'))['setObjToUrlParams']
  const shallowReactive: (typeof import('vue'))['shallowReactive']
  const shallowReadonly: (typeof import('vue'))['shallowReadonly']
  const shallowRef: (typeof import('vue'))['shallowRef']
  const storage: (typeof import('./src/utils/storage'))['default']
  const storeToRefs: (typeof import('pinia'))['storeToRefs']
  const throttle: (typeof import('./src/utils/index'))['throttle']
  const toDouble: (typeof import('./src/utils/dateUtils'))['toDouble']
  const toRaw: (typeof import('vue'))['toRaw']
  const toRef: (typeof import('vue'))['toRef']
  const toRefs: (typeof import('vue'))['toRefs']
  const toValue: (typeof import('vue'))['toValue']
  const triggerRef: (typeof import('vue'))['triggerRef']
  const unref: (typeof import('vue'))['unref']
  const useAttrs: (typeof import('vue'))['useAttrs']
  const useCssModule: (typeof import('vue'))['useCssModule']
  const useCssVars: (typeof import('vue'))['useCssVars']
  const useDefer: (typeof import('./src/utils/useDefer'))['useDefer']
  const useId: (typeof import('vue'))['useId']
  const useLink: (typeof import('vue-router'))['useLink']
  const useModel: (typeof import('vue'))['useModel']
  const useMounted: (typeof import('./src/utils/index'))['useMounted']
  const useResizeObserver: (typeof import('./src/utils/index'))['useResizeObserver']
  const useRoute: (typeof import('vue-router'))['useRoute']
  const useRouter: (typeof import('vue-router'))['useRouter']
  const useSlots: (typeof import('vue'))['useSlots']
  const useSlotsExist: (typeof import('./src/utils/index'))['useSlotsExist']
  const useSupported: (typeof import('./src/utils/index'))['useSupported']
  const useTemplateRef: (typeof import('vue'))['useTemplateRef']
  const warn: (typeof import('./src/utils/log'))['warn']
  const watch: (typeof import('vue'))['watch']
  const watchEffect: (typeof import('vue'))['watchEffect']
  const watchPostEffect: (typeof import('vue'))['watchPostEffect']
  const watchSyncEffect: (typeof import('vue'))['watchSyncEffect']
}
// for type re-export
declare global {
  // @ts-ignore
  export type {
    Component,
    Slot,
    Slots,
    ComponentPublicInstance,
    ComputedRef,
    DirectiveBinding,
    ExtractDefaultPropTypes,
    ExtractPropTypes,
    ExtractPublicPropTypes,
    InjectionKey,
    PropType,
    Ref,
    ShallowRef,
    MaybeRef,
    MaybeRefOrGetter,
    VNode,
    WritableComputedRef
  } from 'vue'
  import('vue')
  // @ts-ignore
  export type { ViewportOffsetResult } from './src/utils/domUtils'
  import('./src/utils/domUtils')
  // @ts-ignore
  export type { Storage } from './src/utils/storage'
  import('./src/utils/storage')
}
