/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    Button: typeof import('vue-amazing-ui')['Button']
    ConfigProvider: typeof import('vue-amazing-ui')['ConfigProvider']
    Flex: typeof import('vue-amazing-ui')['Flex']
    GradientText: typeof import('vue-amazing-ui')['GradientText']
    Message: typeof import('vue-amazing-ui')['Message']
    Modal: typeof import('vue-amazing-ui')['Modal']
    Result: typeof import('vue-amazing-ui')['Result']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}
